# Generated by Django 5.1.6 on 2025-06-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_key",
            field=models.CharField(
                blank=True,
                help_text="AES-GCM encrypted personal user key (base64)",
                max_length=512,
                null=True,
            ),
        ),
    ]
