services:
  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "8080:80"
    # Mount the build folder to serve updated files without rebuilding the image
    volumes:
      - ./build:/usr/share/nginx/html:ro
    networks:
      - ogtickets_nw

networks:
  ogtickets_nw:
    external: true
