services:
  builder:
    image: node:16-alpine
    working_dir: /app
     # Install dependencies and run watch build using chokidar-cli
    environment:
      SHELL: /bin/sh
    command: sh -c "npm install && npm run watch:build"
    volumes:
      - ./:/app
    networks:
      - ogtickets_nw

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "8080:80"
    # Mount the build folder to serve updated files without rebuilding the image
    volumes:
      - ./build:/usr/share/nginx/html:ro
    networks:
      - ogtickets_nw

networks:
  ogtickets_nw:
    external: true
