# This file is only used in test
services:
  db:
    image: postgres:14
    restart: on-failure
    environment:
      POSTGRES_DB: test_ogtickets_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    networks:
      - test_net

  test:
    image: tixidest/ogtickets-backend:latest
    environment:
      ENV: test
      DEBUG: "True"
      SECRET_KEY: "test_dummy-secret-key&1234"
      DB_NAME:  "test_ogtickets_db"
      DB_USER: "test_user"
      DB_PASSWORD: "test_password"
      DB_HOST: db
      DB_PORT: "5432"
      EMAIL_BACKEND: "django.core.mail.backends.locmem.EmailBackend"
      FRONT_BASE_URL: "http://testserver"
      FRONT_ACTIVATION_ROUTE: "/acces/ouverture"
      FRONT_PASSWORD_RESET_ROUTE: "/acces/reprise"
    depends_on:
      - db
    networks:
      - test_net
    command: sh start-test.sh

networks:
  test_net:
