# This file is only used in development, localy, to run the backend service in a container.
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./secrets/db_password.txt:/run/secrets/db_password:ro
    ports:
      - "5434:5432"
    networks:
      - ogtickets_nw

  backend:
    image: tixidest/ogtickets-backend:latest
    ports:
      - "8000:8000"
    environment:
      ENV: dev
      DEBUG: "True"
    volumes:
      - ./secrets/secret_key.txt:/run/secrets/secret_key:ro
      - ./secrets/db_user.txt:/run/secrets/db_user:ro
      - ./secrets/db_password.txt:/run/secrets/db_password:ro
      - ./secrets/db_name.txt:/run/secrets/db_name:ro
      - ./secrets/db_host.txt:/run/secrets/db_host:ro
      - ./secrets/allowed_hosts.txt:/run/secrets/allowed_hosts:ro
      - ./secrets/sentry_dsn.txt:/run/secrets/sentry_dsn:ro
      - ./secrets/email_host.txt:/run/secrets/email_host:ro
      - ./secrets/email_port.txt:/run/secrets/email_port:ro
      - ./secrets/email_host_user.txt:/run/secrets/email_host_user:ro
      - ./secrets/email_host_password.txt:/run/secrets/email_host_password:ro
      - ./secrets/email_use_tls.txt:/run/secrets/email_use_tls:ro
      - ./secrets/default_from_email.txt:/run/secrets/default_from_email:ro
      - ./start-env-dev.sh:/start-env-dev.sh
    depends_on:
      - db
    networks:
      - ogtickets_nw

networks:
  ogtickets_nw:
    external: true

volumes:
  postgres_data:
