# This file is only used in development, localy, to run the backend service in a container.
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - ogtickets_nw

  backend:
    image: tixidest/ogtickets-backend:latest
    ports:
      - "8000:8000"
    environment:
      ENV: dev
      DEBUG: "True"
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      SENTRY_DSN: ${SENTRY_DSN}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
    volumes:
      - ./secrets/secret_key.txt:/run/secrets/secret_key:ro
      - ./secrets/db_user.txt:/run/secrets/db_user:ro
      - ./secrets/db_password.txt:/run/secrets/db_password:ro
      - ./secrets/db_name.txt:/run/secrets/db_name:ro
      - ./secrets/db_host.txt:/run/secrets/db_host:ro
      - ./secrets/allowed_hosts.txt:/run/secrets/allowed_hosts:ro
      - ./secrets/sentry_dsn.txt:/run/secrets/sentry_dsn:ro
      - ./secrets/email_host.txt:/run/secrets/email_host:ro
      - ./secrets/email_port.txt:/run/secrets/email_port:ro
      - ./secrets/email_host_user.txt:/run/secrets/email_host_user:ro
      - ./secrets/email_host_password.txt:/run/secrets/email_host_password:ro
      - ./secrets/email_use_tls.txt:/run/secrets/email_use_tls:ro
      - ./secrets/default_from_email.txt:/run/secrets/default_from_email:ro
    command: sh /start.sh
    depends_on:
      - db
    networks:
      - ogtickets_nw

networks:
  ogtickets_nw:
    external: true

volumes:
  postgres_data:
