services:
  backend:
    image: tixidest/ogtickets-backend:latest
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    environment:
      ENV: prod
      DEBUG: false
      FRONT_BASE_URL: https://og-tickets.vercel.app
      EMAIL_USE_TLS: true
      EMAIL_HOST_USER: noreply@ogtickets.space
      EMAIL_PORT: 587
      DEFAULT_FROM_EMAIL: 'Ne pas répondre - comptes utilisateur <noreply@ogtickets.space>'
      FRONT_BASE_URL: "http://testserver"
      FRONT_ACTIVATION_ROUTE: "/acces/ouverture"
      FRONT_PASSWORD_RESET_ROUTE: "/acces/reprise"
    secrets:
      - source: secret_key
      - source: db_name
      - source: db_host
      - source: db_user
      - source: db_password
      - source: allowed_hosts
      - source: cors_allowed_origins
      - source: email_host
      - source: email_host_password
      - source: sentry_dsn
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.2'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
      labels:
        - 'space.ogtickets.description=Backend service for ogtickets.space'

secrets:
  secret_key:
    external: true
  db_name:
    external: true
  db_host:
    external: true
  db_user:
    external: true
  db_password:
    external: true
  allowed_hosts:
    external: true
  cors_allowed_origins:
    external: true
  email_host:
    external: true
  email_host_password:
    external: true
  sentry_dsn:
    external: true
