services:
  backend:
    image: tixidest/ogtickets-backend:latest
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    environment:
      ENV: prod
    secrets:
      - source: secret_key
        target: SECRET_KEY
      - source: db_password
        target: DATABASE_PASSWORD
      - source: sentry_dsn
        target: SENTRY_DSN
      - source: db_user
        target: DATABASE_USER
      - source: db_name
        target: DATABASE_NAME
      - source: db_host
        target: DATABASE_HOST
      - source: allowed_hosts
        target: ALLOWED_HOSTS
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "0.2"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 256M
      labels:
        - "org.duckdns.ogtickets.description=Backend service for ogtickets.duckdns.org"

secrets:
  secret_key:
    file: secrets/django_secret_key.txt
  DB_USER:
    file: secrets/db_user.txt
  DB_PASSWORD:
    file: secrets/db_password.txt
  DB_NAME:
    file: secrets/db_name.txt
  DB_HOST:
    file: secrets/db_host.txt
  ALLOWED_HOSTS:
    file: secrets/allowed_hosts.txt
  SENTRY_DSN:
    file: secrets/sentry_dsn.txt
