# Anchor definition for common environment variables
x-common-env: &common-env
  ENV: prod
  DEBUG: 'false'
  CSRF_TRUSTED_ORIGIN: 'https://ogtickets.space'
  EMAIL_USE_TLS: 'true'
  EMAIL_HOST_USER: noreply@ogtickets.space
  EMAIL_PORT: 587
  DEFAULT_FROM_EMAIL: 'Ne pas répondre - comptes utilisateur <noreply@ogtickets.space>'
  FRONTEND_DOMAIN: ogtickets.space
  USERS_ACTIVATION_ROUTE: 'acces/ouverture'
  USERS_PASSWORD_RESET_ROUTE: 'acces/reprise'
  REDIS_URL: redis://redis:6379/0
  CELERY_BROKER_URL: redis://redis:6379/0
  CELERY_RESULT_BACKEND: redis://redis:6379/0
  CELERY_TASK_ALWAYS_EAGER: 'False'
  CELERY_TASK_EAGER_PROPAGATES: 'False'

# Define common secrets
x-common-secrets: &common-secrets
  - secret_key
  - db_user
  - db_password
  - db_name
  - db_host
  - allowed_hosts
  - sentry_dsn
  - email_host
  - email_host_password
  - stripe_secret_key
  - stripe_webhook_secret
  - ticket_encryption_key
  - ticket_hmac_key

services:
  redis:
    image: redis:7-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - ogtickets_nw

  backend:
    image: tixidest/ogtickets-backend:latest
    command: ['django']
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    environment:
      <<: *common-env
    secrets: *common-secrets
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.2'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
      labels:
        - 'space.ogtickets.description=Backend service for ogtickets.space'
    networks:
      - ogtickets_nw

  celery_worker:
    image: tixidest/ogtickets-backend:latest
    command: ['celery']
    environment:
      <<: *common-env
    secrets: *common-secrets
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.1'
          memory: 256M
        reservations:
          cpus: '0.05'
          memory: 128M
    networks:
      - ogtickets_nw

secrets:
  secret_key:
    external: true
  db_name:
    external: true
  db_host:
    external: true
  db_user:
    external: true
  db_password:
    external: true
  allowed_hosts:
    external: true
  email_host:
    external: true
  email_host_password:
    external: true
  sentry_dsn:
    external: true
  stripe_secret_key:
    external: true
  stripe_webhook_secret:
    external: true
  ticket_encryption_key:
    external: true
  ticket_hmac_key:
    external: true

networks:
  ogtickets_nw:
    driver: overlay
