services:
  backend:
    image: tixidest/ogtickets-backend:latest
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    environment:
      ENV: prod
    secrets:
      - source: secret_key
      - source: db_password
      - source: sentry_dsn
      - source: db_user
      - source: db_name
      - source: db_host
      - source: cors_allowed_origins
      - source: allowed_hosts
      - source: email_host
      - source: email_port
      - source: email_host_user
      - source: email_host_password
      - source: email_use_tls
      - source: default_from_email
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.2'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
      labels:
        - 'org.duckdns.ogtickets.description=Backend service for ogtickets.duckdns.org'

secrets:
  secret_key:
    file: secrets/secret_key.txt
  db_user:
    file: secrets/db_user.txt
  db_password:
    file: secrets/db_password.txt
  db_name:
    file: secrets/db_name.txt
  db_host:
    file: secrets/db_host.txt
  allowed_hosts:
    file: secrets/allowed_hosts.txt
  cors_allowed_origins:
    file: secrets/cors_allowed_origins.txt
  sentry_dsn:
    file: secrets/sentry_dsn.txt
  email_host:
    file: secrets/email_host.txt
  email_port:
    file: secrets/email_port.txt
  email_host_user:
    file: secrets/email_host_user.txt
  email_host_password:
    file: secrets/email_host_password.txt
  email_use_tls:
    file: secrets/email_use_tls.txt
  default_from_email:
    file: secrets/default_from_email.txt
