services:
  backend:
    image: tixidest/ogtickets-backend:latest
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    environment:
      ENV: prod
    secrets:
      - source: secret_key
      - source: db_password
      - source: sentry_dsn
      - source: db_user
      - source: db_name
      - source: db_host
      - source: cors_allowed_origins
      - source: allowed_hosts
      - source: email_host
      - source: email_port
      - source: email_host_user
      - source: email_host_password
      - source: email_use_tls
      - source: default_from_email
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.2'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
      labels:
        - 'space.ogtickets.description=Backend service for ogtickets.space'

secrets:
  secret_key:
    external: true
  db_user:
    external: true
  db_password:
    external: true
  db_name:
    external: true
  db_host:
    external: true
  allowed_hosts:
    external: true
  cors_allowed_origins:
    external: true
  sentry_dsn:
    external: true
  email_host:
    external: true
  email_port:
    external: true
  email_host_user:
    external: true
  email_host_password:
    external: true
  email_use_tls:
    external: true
  default_from_email:
    external: true
