# Generated by Django 5.1.6 on 2025-05-21 22:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ordered_at__isnull", True)),
                fields=("custom_user",),
                name="unique_open_cart_per_user",
            ),
        ),
    ]
