import { makeAuthPostRequest } from '../utils/authRequest';

/**
 * Activates a user account using the provided activation token
 * @param {string} uid - The user's unique activation ID encoded in base64
 * @param {string} token - The activation token generated by the server
 * @returns {Promise<object>} Resolves with server response on success
 * @throws {Error} Throws with server error message or default activation failure message
 */
export const activateAccount = (uid, token) =>
  makeAuthPostRequest('users/activation', { uid, token }, 'Activation');

/**
 * Resends account activation email to the provided email address
 * @param {string} email - The email address associated with the pending activation
 * @returns {Promise<object>} Resolves with server response on success
 * @throws {Error} Throws with server error message or default resend failure message
 */
export const resendActivation = (email) =>
  makeAuthPostRequest(
    'users/resend_activation',
    { email },
    'Resend activation link'
  );
