# Generated by Django 5.1.6 on 2025-06-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="nb_place",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Nombre de personnes incluses dans l'offre"
            ),
        ),
    ]
